# Generated by Django 5.2 on 2025-07-11 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='taskswap',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='taskswap',
            name='requester_task',
            field=models.ForeignKey(default=1, help_text='Task that the requester wants to give away', on_delete=django.db.models.deletion.CASCADE, related_name='swap_requests_as_requester', to='tasks.task'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taskswap',
            name='target_task',
            field=models.ForeignKey(default=1, help_text='Task that the requester wants to receive', on_delete=django.db.models.deletion.CASCADE, related_name='swap_requests_as_target', to='tasks.task'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='taskswap',
            name='task',
        ),
    ]
